version: "3"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: nodejs
    container_name: backend
    depends_on:
      - db
    links:
      - db
    environment:
      WAIT_HOSTS: db:27017
    restart: unless-stopped
    volumes:
      - ./server:/frontend
    ports:
      - "9000:9000"

  db:
    container_name: db
    image: mongo
    restart: always
    user: root
    environment:
      - MONGO_INITDB_ROOT_USERNAME=paperclicks
      - MONGO_INITDB_DATABASE=paperclicks
      - MONGO_INITDB_ROOT_PASSWORD=paperclickspssw
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  frontend:
    container_name: frontend
    build:
      context: ./paperclick
    volumes:
      - ./paperclick:/frontend
    ports:
      - "8080:8080"
